name: Build & Push Flask Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- Create Dockerfile dynamically ----
      - name: Create Dockerfile
        run: |
          echo "FROM python:3.10-slim" > Dockerfile
          echo "" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "" >> Dockerfile
          echo "COPY requirements.txt ." >> Dockerfile
          echo "RUN pip install --no-cache-dir -r requirements.txt" >> Dockerfile
          echo "" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "" >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile
          echo "" >> Dockerfile
          echo 'CMD ["python", "app.py"]' >> Dockerfile

      # ---- Login to DockerHub ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build & Push Image ----
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

      - name: Print Success
        run: echo "Flask Docker image pushed successfully!"
